# Generated by Django 6.1.1 on 2026-09-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('checkout_minutes', models.PositiveSmallIntegerField()),
                ('stayover_minutes', models.PositiveSmallIntegerField()),
                ('vacant_minutes', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
