# Generated by Django 6.1.1 on 2026-09-22 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_staff_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checkout', 'Checkout'), ('stayover', 'Stay-over'), ('vacant', 'Vacant'), ('ooo', 'Out of Order')], max_length=10)),
                ('is_vip', models.BooleanField(default=True)),
                ('vip_extra_minutes', models.PositiveSmallIntegerField(default=0)),
                ('ready_by', models.TimeField(blank=True, null=True)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_statuses', to='planner.dayplan')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.room')),
            ],
            options={
                'verbose_name_plural': 'room statuses',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.staff')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='planner.roomstatus')),
            ],
            options={
                'ordering': ['staff', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='roomstatus',
            constraint=models.UniqueConstraint(fields=('day_plan', 'room'), name='one_status_per_room_per_day'),
        ),
    ]
